### ISSUE TITLE
Can not see Marker property value from sharedAction CallSequence

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#108]
In a sharedAction if you add a CallSequence bean with a marker you can not source it in the picker from a bean in your Application Page.
I have attached a project to demonstrate this issue (rename *.zip to *.car).
There is an error log associated to the marker in the CallSequence of the SharedAction I didn't notice before:

> (0.12) Error occured when calling #MY_SHARED_MARKER:Error: 'http://localhost:18080/convertigo/projects/sharedmarker' is not a valid Convertigo endpoint
    at new C8oException (D:/COMMON/C8O/sc760_64_dark/workspace/sharedmarker/_private/ionic/node_modules/c8osdkangular/fesm5/c8osdkangular.js:703:28)
    at C8oCore.call (D:/COMMON/C8O/sc760_64_dark/workspace/sharedmarker/_private/ionic/node_modules/c8osdkangular/fesm5/c8osdkangular.js:6932:23)
    at C8oCore.callJsonObject (D:/COMMON/C8O/sc760_64_dark/workspace/sharedmarker/_private/ionic/node_modules/c8osdkangular/fesm5/c8osdkangular.js:7050:14)
    at eval (D:/COMMON/C8O/sc760_64_dark/workspace/sharedmarker/_private/ionic/node_modules/c8ocaf/src/caf/convertigo.router.ts:178:23)
    at new t (http://localhost:8100/build/polyfills.js:3:21506)
    at C8oRouter.c8oCall (D:/COMMON/C8O/sc760_64_dark/workspace/sharedmarker/_private/ionic/node_modules/c8ocaf/src/caf/convertigo.router.ts:165:16)
    at eval (D:/COMMON/C8O/sc760_64_dark/workspace/sharedmarker/_private/ionic/node_modules/c8ocaf/src/caf/convertigo.base.ts:67:34)
    at new t (http://localhost:8100/build/polyfills.js:3:21506)
    at Page.C8oPageBase.call (D:/COMMON/C8O/sc760_64_dark/workspace/sharedmarker/_private/ionic/node_modules/c8ocaf/src/caf/convertigo.base.ts:66:16)
    at eval (D:/COMMON/C8O/sc760_64_dark/workspace/sharedmarker/_private/ionic/src/services/actionbeans.service.ts:89:18)

[sharedmarker.zip](https://github.com/convertigo/convertigo/files/3173207/sharedmarker.zip)

**Comment by nathalie-lammelin** [comment]
The error (above) is due to the fact that the callsequence under the sharedaction has **NO** sequence attributed, just a marker.

Here is the project fixed with the sequence:
[sharedmarker.zip](https://github.com/convertigo/convertigo/files/3192050/sharedmarker.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03052-develop-7.6.0-beta)**
