### ISSUE TITLE
Studio: NPE in Stdout console when selecting LogView 

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#116]
Here is the exception:
```
### !ENTRY org.eclipse.e4.ui.workbench 4 0 2019-05-24 16:40:02.576
!MESSAGE Error setting focus to : org.eclipse.e4.ui.model.application.ui.basic.impl.PartImpl Engine Log
!STACK 0
java.lang.NullPointerException
	at com.twinsoft.convertigo.eclipse.views.loggers.EngineLogView.setFocus(EngineLogView.java:1019)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.delegateSetFocus(CompatibilityPart.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:326)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:248)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:147)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.focusGui(PartRenderingEngine.java:808)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:769)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:684)
	at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:97)
```
Steps to reproduce:
1. Launch the Studio.
    Select the `EngineLog` view, **uncheck 'Activate on new events' option**.
    Select the `Stdout` console, clear it.
    Exit the Studio.
2. Launch the Studio. The `Stdout` console is activated (has focus)
    Now select the `EngineLog` view: it is activated and  empty. Wait for logs to be appended.
    Now select back the `Stdout` console: you should see the above NPE

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 7.6.0_beta (build 03693-develop-7.6.0-beta)**
