### ISSUE TITLE
Mobile Builder: navParam not up-to-date

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#177]
I have 2 pages : Page1 and Page2.
Same structure : button with a CallSequence then a Push/Root Page to the other Page with the Sequence result in "Page data". The Sequence return a timestamp.

**this.navParams.data** is ok 1/2 times.

Nothing to do with navParam, but their is this error for an empty Requestable for the CallSequence action : 
```
(3.873) Error occured when calling :Error: 'http://localhost:18080/convertigo/projects/MB762' is not a valid Convertigo endpoint
    at new C8oException (C:/Standalone/C8O/Studio_7.6.2_beta/workspace/MB762/_private/ionic/node_modules/c8osdkangular/fesm5/c8osdkangular.js:476:28)
    at C8oCore.call (C:/Standalone/C8O/Studio_7.6.2_beta/workspace/MB762/_private/ionic/node_modules/c8osdkangular/fesm5/c8osdkangular.js:5341:23)
    at C8oCore.callJsonObject (C:/Standalone/C8O/Studio_7.6.2_beta/workspace/MB762/_private/ionic/node_modules/c8osdkangular/fesm5/c8osdkangular.js:5415:14)
    at eval (C:/Standalone/C8O/Studio_7.6.2_beta/workspace/MB762/_private/ionic/node_modules/c8ocaf/src/caf/convertigo.router.ts:181:23)
    at new t (http://localhost:8100/build/polyfills.js:3:21506)
    at C8oRouter.c8oCall (C:/Standalone/C8O/Studio_7.6.2_beta/workspace/MB762/_private/ionic/node_modules/c8ocaf/src/caf/convertigo.router.ts:168:16)
    at eval (C:/Standalone/C8O/Studio_7.6.2_beta/workspace/MB762/_private/ionic/node_modules/c8ocaf/src/caf/convertigo.base.ts:73:34)
    at new t (http://localhost:8100/build/polyfills.js:3:21506)
    at Page3.C8oPageBase.call (C:/Standalone/C8O/Studio_7.6.2_beta/workspace/MB762/_private/ionic/node_modules/c8ocaf/src/caf/convertigo.base.ts:72:16)
    at eval (C:/Standalone/C8O/Studio_7.6.2_beta/workspace/MB762/_private/ionic/src/services/actionbeans.service.ts:87:26)
```
 See attached project.
[MB762.zip](https://github.com/convertigo/convertigo/files/3450697/MB762.zip)

**Comment by CharlesGrimont** [comment]
You need to use a marker
