### ISSUE TITLE
lib_AmzonLEX: error while opening project.

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#224]
**Convertigo EMS Studio 7.7.0_beta (build 05147-develop-7.7.0-beta)**
TPL version 7.6.0.5
Same error using TPL 7.7.0.5

![image](https://user-images.githubusercontent.com/1685373/66653353-1966c500-ec38-11e9-93da-e230451b45fd.png)

Error log view:

> eclipse.buildId=unknown
java.version=11.0.4
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

> com.twinsoft.convertigo.eclipse.ConvertigoPlugin
Error
Fri Oct 11 14:56:09 CEST 2019
Error while introspecting parameter "animationName"

> java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.DatabaseObjectTreeObject.findPropertyDescriptor(DatabaseObjectTreeObject.java:465)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.DatabaseObjectTreeObject.getDescriptors(DatabaseObjectTreeObject.java:357)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.DatabaseObjectTreeObject.<init>(DatabaseObjectTreeObject.java:166)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.MobileComponentTreeObject.<init>(MobileComponentTreeObject.java:54)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.MobileUIComponentTreeObject.<init>(MobileUIComponentTreeObject.java:103)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1640)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:203)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:152)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:126)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:98)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:72)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.init(ProjectExplorerView.java:1522)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView.loadDatabaseObject(ProjectExplorerView.java:1946)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView.loadDatabaseObject(ProjectExplorerView.java:1501)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectLoadingJob.loadDatabaseObject(ProjectLoadingJob.java:299)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectLoadingJob.run(ProjectLoadingJob.java:183)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
	at com.twinsoft.convertigo.beans.mobile.components.CssAnimation.names(CssAnimation.java:140)
	at com.twinsoft.convertigo.beans.mobile.components.UIAnimation.getTagsForProperty(UIAnimation.java:80)
	at com.twinsoft.convertigo.eclipse.property_editors.StringComboBoxPropertyDescriptor.getTags(StringComboBoxPropertyDescriptor.java:268)
	... 39 more
Root exception:
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
	at com.twinsoft.convertigo.beans.mobile.components.CssAnimation.names(CssAnimation.java:140)
	at com.twinsoft.convertigo.beans.mobile.components.UIAnimation.getTagsForProperty(UIAnimation.java:80)
	at com.twinsoft.convertigo.eclipse.property_editors.StringComboBoxPropertyDescriptor.getTags(StringComboBoxPropertyDescriptor.java:268)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.DatabaseObjectTreeObject.findPropertyDescriptor(DatabaseObjectTreeObject.java:465)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.DatabaseObjectTreeObject.getDescriptors(DatabaseObjectTreeObject.java:357)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.DatabaseObjectTreeObject.<init>(DatabaseObjectTreeObject.java:166)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.MobileComponentTreeObject.<init>(MobileComponentTreeObject.java:54)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.MobileUIComponentTreeObject.<init>(MobileUIComponentTreeObject.java:103)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1640)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:219)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:203)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:152)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:126)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:98)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1936)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:72)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.init(ProjectExplorerView.java:1522)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView.loadDatabaseObject(ProjectExplorerView.java:1946)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView.loadDatabaseObject(ProjectExplorerView.java:1501)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectLoadingJob.loadDatabaseObject(ProjectLoadingJob.java:299)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectLoadingJob.run(ProjectLoadingJob.java:183)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06082-develop-7.7.0-beta)**
