### ISSUE TITLE
[MB] Renaming a Page name breaks Application build

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#265]
in **Convertigo EMS Studio 7.7.0_beta (build 05968-develop-7.7.0-beta)**

- Create a new Page
- Rename it
- Add UI components to page. There is no auto build.
- Force application rebuild by clicking build mode button or reopening Application tab.

Generates following error:

> !Engine                       | 2019-11-25 19:03:49,564 | DEBUG | Worker-15: Opening project MB_770_05968 | (MobileBuilder) Template version: 7.7.0.13 for ionic project 'MB_770_05968'
> !Engine                       | 2019-11-25 19:03:49,736 | DEBUG | Worker-15: Opening project MB_770_05968 | (MobileBuilder) Initialized builder for ionic project 'MB_770_05968'
> !Studio                       | 2019-11-25 19:03:59,999 | INFO  | main                             | npm -version: [0] 5.5.1
> !Engine                       | 2019-11-25 19:04:00,412 | DEBUG | main                             | (MobileBuilder) AutoBuild mode set to ON
> !Engine                       | 2019-11-25 19:04:00,413 | DEBUG | main                             | (MobileBuilder) AutoBuild mode set to ON
> !Studio                       | 2019-11-25 19:04:05,027 | INFO  | ConvertigoExecutor-1624          | Handle application assets
> !Studio                       | 2019-11-25 19:04:06,584 | INFO  | ConvertigoExecutor-1624          | > Convertigo-template-app@ ionic:serve:eval D:\COMMON\C8O\sc770_64\workspace\MB_770_05968\_private\ionic
> !Studio                       | 2019-11-25 19:04:06,588 | INFO  | ConvertigoExecutor-1624          | > ionic-app-scripts serve --enableLint false --sourceMapType eval "8102" "35731" "53705"
> !Studio                       | 2019-11-25 19:04:09,427 | INFO  | ConvertigoExecutor-1624          | [19:04:09]  ionic-app-scripts 3.2.4 
> !Studio                       | 2019-11-25 19:04:09,457 | INFO  | ConvertigoExecutor-1624          | [19:04:09]  watch started ... 
> !Studio                       | 2019-11-25 19:04:09,510 | INFO  | ConvertigoExecutor-1624          | [19:04:09]  build dev started ... 
> !Studio                       | 2019-11-25 19:04:09,512 | INFO  | ConvertigoExecutor-1624          | [19:04:09]  clean started ... 
> !Studio                       | 2019-11-25 19:04:09,515 | INFO  | ConvertigoExecutor-1624          | [19:04:09]  clean finished in 1 ms 
> !Studio                       | 2019-11-25 19:04:09,519 | INFO  | ConvertigoExecutor-1624          | [19:04:09]  copy started ... 
> !Studio                       | 2019-11-25 19:04:09,606 | INFO  | ConvertigoExecutor-1624          | [19:04:09]  deeplinks started ... 
> !Studio                       | 2019-11-25 19:04:09,682 | INFO  | ConvertigoExecutor-1624          | [19:04:09]  ionic-app-script task: "serve" 
> !Studio                       | 2019-11-25 19:04:09,685 | INFO  | ConvertigoExecutor-1624          | [19:04:09]  Error: There are multiple entries in the deeplink config with the segment of path-to-page 
> !Studio                       | 2019-11-25 19:04:09,688 | INFO  | ConvertigoExecutor-1624          | Error: There are multiple entries in the deeplink config with the segment of path-to-page
> !Studio                       | 2019-11-25 19:04:09,692 | INFO  | ConvertigoExecutor-1624          |     at new BuildError (D:\COMMON\C8O\sc770_64\workspace\MB_770_05968\_private\ionic\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
> !Studio                       | 2019-11-25 19:04:09,694 | INFO  | ConvertigoExecutor-1624          |     at D:\COMMON\C8O\sc770_64\workspace\MB_770_05968\_private\ionic\node_modules\@ionic\app-scripts\dist\deep-linking.js:57:21
> !Studio                       | 2019-11-25 19:04:09,696 | INFO  | ConvertigoExecutor-1624          |     at <anonymous>
> !Studio                       | 2019-11-25 19:04:09,734 | INFO  | ConvertigoExecutor-1624          | npm ERR! code ELIFECYCLE
> !Studio                       | 2019-11-25 19:04:09,736 | INFO  | ConvertigoExecutor-1624          | npm ERR! errno 1
> !Studio                       | 2019-11-25 19:04:09,739 | INFO  | ConvertigoExecutor-1624          | npm ERR! Convertigo-template-app@ ionic:serve:eval: `ionic-app-scripts serve --enableLint false --sourceMapType eval "8102" "35731" "53705"`
> !Studio                       | 2019-11-25 19:04:09,742 | INFO  | ConvertigoExecutor-1624          | npm ERR! Exit status 1
> !Studio                       | 2019-11-25 19:04:09,745 | INFO  | ConvertigoExecutor-1624          | npm ERR! 
> !Studio                       | 2019-11-25 19:04:09,748 | INFO  | ConvertigoExecutor-1624          | npm ERR! Failed at the Convertigo-template-app@ ionic:serve:eval script.
> !Studio                       | 2019-11-25 19:04:09,750 | INFO  | ConvertigoExecutor-1624          | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> !Studio                       | 2019-11-25 19:04:09,753 | INFO  | ConvertigoExecutor-1624          | npm ERR! A complete log of this run can be found in:
> !Studio                       | 2019-11-25 19:04:09,756 | INFO  | ConvertigoExecutor-1624          | npm ERR!     C:\Users\gregoryv\AppData\Roaming\npm-cache\_logs\2019-11-25T18_04_09_736Z-debug.log

[2019-11-25T18_04_09_736Z-debug.log](https://github.com/convertigo/convertigo/files/3888003/2019-11-25T18_04_09_736Z-debug.log)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06066-develop-7.7.0-beta)**
