### ISSUE TITLE
Bad deployment if the ".car" is dropped in the workspace

### ISSUE THREAD

**Issue by do91** [convertigo/convertigo#28]
On server version version 7.6.0_beta (build 01230-feature-3-UrlMapper_v2-7.6.0-beta), if we copy a project xxx.car in project workspace and start the server, the project is not deployed.

There is an error:
!Engine                       | 2018-11-15 14:17:34,037 | ERROR | MigrationJob #ReadLogFiles       | An error occured while migrating project "ReadLogFiles".
com.twinsoft.convertigo.engine.EngineException: Unable to update the project from the file "/workspace/projects/ReadLogFiles.car".
	at com.twinsoft.convertigo.engine.DatabaseObjectsManager.updateProject(DatabaseObjectsManager.java:706)
	at com.twinsoft.convertigo.engine.DatabaseObjectsManager.updateProject(DatabaseObjectsManager.java:644)
	at com.twinsoft.convertigo.engine.MigrationJob.run(MigrationJob.java:55)
Caused by: com.twinsoft.convertigo.engine.EngineException: Unable to retrieve project's version from "/workspace/projects/ReadLogFiles.car".
	at com.twinsoft.convertigo.engine.DatabaseObjectsManager.needsMigration(DatabaseObjectsManager.java:1050)
	at com.twinsoft.convertigo.engine.DatabaseObjectsManager.updateProject(DatabaseObjectsManager.java:663)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03052-develop-7.6.0-beta)**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Server 7.6.0_beta (build 03052-develop-7.6.0-beta)**
