### ISSUE TITLE
Tooltip component does not work with TPL 7.7.0.14

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#284]
Sample project attached below.
Open Page_Tooltip page

Runtime Error
Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead. Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead. at new BrowserModule (http://localhost:8100/build/vendor.js:48025:19) at _createClass (http://localhost:8100/build/vendor.js:11308:20) at _createProviderInstance$1 (http://localhost:8100/build/vendor.js:11282:26) at initNgModule (http://localhost:8100/build/vendor.js:11235:28) at new NgModuleRef_ (http://localhost:8100/build/vendor.js:12490:9) at createNgModuleRef (http://localhost:8100/build/vendor.js:12479:12) at Object.debugCreateNgModuleRef [as createNgModuleRef] (http://localhost:8100/build/vendor.js:14813:12) at NgModuleFactory_.create (http://localhost:8100/build/vendor.js:15951:25) at http://localhost:8100/build/vendor.js:72427:36 at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
Stack
Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
    at new BrowserModule (http://localhost:8100/build/vendor.js:48025:19)
    at _createClass (http://localhost:8100/build/vendor.js:11308:20)
    at _createProviderInstance$1 (http://localhost:8100/build/vendor.js:11282:26)
    at initNgModule (http://localhost:8100/build/vendor.js:11235:28)
    at new NgModuleRef_ (http://localhost:8100/build/vendor.js:12490:9)
    at createNgModuleRef (http://localhost:8100/build/vendor.js:12479:12)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (http://localhost:8100/build/vendor.js:14813:12)
    at NgModuleFactory_.create (http://localhost:8100/build/vendor.js:15951:25)
    at http://localhost:8100/build/vendor.js:72427:36
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:60661:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:60654:14)
    at http://localhost:8100/build/vendor.js:60701:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:5135:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
Ionic Framework: 3.9.9
Ionic App Scripts: 3.2.4
Angular Core: 5.2.11
Angular Compiler CLI: 5.2.11
Node: 8.9.1
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Android

[MobileBuilderComponents.zip](https://github.com/convertigo/convertigo/files/3961875/MobileBuilderComponents.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06351-develop-7.7.0-beta)**
