### ISSUE TITLE
Null pointer exception  while importing JSON WS reference

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#299]
We have a :
```
Unable to create connector
java.lang.NullPointerException
	at com.twinsoft.convertigo.engine.util.SwaggerUtils.createRestConnector(SwaggerUtils.java:605)
	at com.twinsoft.convertigo.engine.util.WsReference.createRestConnector(WsReference.java:358)
	at com.twinsoft.convertigo.engine.util.WsReference.importRestWebService(WsReference.java:306)
	at com.twinsoft.convertigo.engine.util.WsReference.importInto(WsReference.java:153)
	at com.twinsoft.convertigo.engine.util.ImportWsReference.importInto(ImportWsReference.java:39)
	at com.twinsoft.convertigo.eclipse.dialogs.WsReferenceImportDialog.run(WsReferenceImportDialog.java:119)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

While importing a json WS definition

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 06733-hotfix-7.7.1-7.7.1-beta)**
