### ISSUE TITLE
Server does not restart properly after clicking "Restart engine" button in administration console

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#362]
Convertigo version 7.8.0 (build 07610-7.8.0)

![image](https://user-images.githubusercontent.com/1685373/83141617-46e17f80-a0f0-11ea-99b6-ea3578185c45.png)

**Comment by gregory-vorbe** [comment]
Seems to work correctly in Convertigo version 7.8.1_beta (build 08056-hotfix-7.8.1-7.8.1-beta).
But I had this error once (can not reproduce anymore):

`java.lang.NullPointerException
	at com.twinsoft.convertigo.engine.admin.services.connections.List.getServiceResult(List.java:92)
	at com.twinsoft.convertigo.engine.admin.services.XmlService.run(XmlService.java:47)
	at com.twinsoft.convertigo.engine.admin.AdminServlet.doRequest(AdminServlet.java:148)
	at com.twinsoft.convertigo.engine.admin.AdminServlet.doPost(AdminServlet.java:76)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.twinsoft.convertigo.engine.servlets.SecurityFilter.doFilter(SecurityFilter.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.twinsoft.convertigo.engine.servlets.CompressionFilter.doFilter(CompressionFilter.java:85)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by gregory-vorbe** [comment]
Previous error not reproduced and not related.
**OK in Convertigo EMS Studio 7.8.1_beta (build 08056-hotfix-7.8.1-7.8.1-beta)**
