### ISSUE TITLE
SchemaManager stackoverflow when projects reference each others

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#398]
When 2 projects reference each others,
Sample of stackoverflow:
```
	at com.twinsoft.convertigo.beans.references.ProjectSchemaReference.getXmlSchemaObject(ProjectSchemaReference.java:68)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:473)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:98)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:497)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:66)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemaForProject(SchemaManager.java:568)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemasForProject(SchemaManager.java:418)
	at com.twinsoft.convertigo.beans.references.ProjectSchemaReference.getXmlSchemaObject(ProjectSchemaReference.java:68)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:473)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:98)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:497)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:66)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemaForProject(SchemaManager.java:568)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemasForProject(SchemaManager.java:418)
	at com.twinsoft.convertigo.beans.references.ProjectSchemaReference.getXmlSchemaObject(ProjectSchemaReference.java:68)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:473)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:98)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:497)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:66)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemaForProject(SchemaManager.java:568)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemasForProject(SchemaManager.java:418)
	at com.twinsoft.convertigo.beans.references.ProjectSchemaReference.getXmlSchemaObject(ProjectSchemaReference.java:68)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:473)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:98)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:497)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:66)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemaForProject(SchemaManager.java:568)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemasForProject(SchemaManager.java:418)
	at com.twinsoft.convertigo.beans.references.ProjectSchemaReference.getXmlSchemaObject(ProjectSchemaReference.java:68)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:473)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:98)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:497)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:66)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemaForProject(SchemaManager.java:568)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemasForProject(SchemaManager.java:418)
	at com.twinsoft.convertigo.beans.references.ProjectSchemaReference.getXmlSchemaObject(ProjectSchemaReference.java:68)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:473)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:98)
	at com.twinsoft.convertigo.engine.SchemaManager$1.walk(SchemaManager.java:497)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:66)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemaForProject(SchemaManager.java:568)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemasForProject(SchemaManager.java:418)
	at com.twinsoft.convertigo.beans.references.ProjectSchemaReference.getXmlSchemaObject(ProjectSchemaReference.java:68)
```

**Comment by nicolas-albert** [comment]
Ok for convertigo-09978-develop-7.9.0-beta
