### ISSUE TITLE
Unhandled IOException when EngineLogView is disposed

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#417]
Error while loading the Engine logs (java.io.IOException)

java.io.IOException: Stream closed
	at java.base/java.io.BufferedReader.ensureOpen(BufferedReader.java:122)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:319)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at com.twinsoft.convertigo.engine.admin.logmanager.LogManager.getLines(LogManager.java:149)
	at com.twinsoft.convertigo.eclipse.views.loggers.EngineLogView.getLogs(EngineLogView.java:1112)
	at com.twinsoft.convertigo.eclipse.views.loggers.EngineLogView$30.run(EngineLogView.java:1048)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by nicolas-albert** [comment]
Ok for convertigo-09978-develop-7.9.0-beta
