### ISSUE TITLE
Null pointer exception when importing a swagger YAML with no summary

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#438]
`
Unable to create connector
java.lang.NullPointerException
	at com.twinsoft.convertigo.engine.util.OpenApiUtils.createRestConnector(OpenApiUtils.java:940)
	at com.twinsoft.convertigo.engine.util.WsReference.createRestConnector(WsReference.java:360)
	at com.twinsoft.convertigo.engine.util.WsReference.importRestWebService(WsReference.java:306)
	at com.twinsoft.convertigo.engine.util.WsReference.importInto(WsReference.java:153)
	at com.twinsoft.convertigo.engine.util.ImportWsReference.importInto(ImportWsReference.java:39)
	at com.twinsoft.convertigo.eclipse.dialogs.WsReferenceImportDialog.run(WsReferenceImportDialog.java:119)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.0_beta (build 10043-develop-7.9.0-beta)**

**Comment by gregory-vorbe** [comment]
If **summary** is present, but empty, the Convertigo **Comment** property is equal to **null**
```
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    get:
      summary: 
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

![image](https://user-images.githubusercontent.com/1685373/106475384-2b601d00-64a6-11eb-936e-9ad94e406fee.png)

**Comment by gregory-vorbe** [comment]
Why do I always think of a new case afterward...
If both **summary** and **description** exist but are blank the **Comment** property displays **null**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.0_beta (build 10075-develop-7.9.0-beta)**
