### ISSUE TITLE
Synchronization issues while using parallel steps in sequencer

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#443]
java.lang.NullPointerException: Cannot invoke "com.twinsoft.convertigo.beans.core.Sequence.getOriginal()" because "this.sequence" is null
	at com.twinsoft.convertigo.beans.core.RequestableStep.stepExecute(RequestableStep.java:852)
	at com.twinsoft.convertigo.beans.core.Step.execute(Step.java:608)
	at com.twinsoft.convertigo.beans.core.StepWithExpressions.executeNextStep(StepWithExpressions.java:686)
	at com.twinsoft.convertigo.beans.steps.BranchStep.executeNextStep(BranchStep.java:96)
	at com.twinsoft.convertigo.beans.core.StepWithExpressions.stepExecute(StepWithExpressions.java:430)
	at com.twinsoft.convertigo.beans.core.Step.execute(Step.java:608)
	at com.twinsoft.convertigo.beans.core.StepWithExpressions$AsynchronousStepThread.run(StepWithExpressions.java:563)

**Comment by nathalie-lammelin** [comment]
Fixed in
[9afd38a](https://github.com/convertigo/convertigo/commit/9afd38ae2aaea9ed6ad55e32c43535792aff84c7)
[952a925](https://github.com/convertigo/convertigo/commit/952a9255a3d19e5f7a3d6d726db2733c36cc6549)

Tested with @opicciotto : ok
