### ISSUE TITLE
SWTException: Widget is disposed in StartupEditor

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#444]
Exception in thread "Browser Thread: 63451" org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4875)
	at org.eclipse.swt.SWT.error(SWT.java:4790)
	at org.eclipse.swt.SWT.error(SWT.java:4761)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:432)
	at org.eclipse.swt.widgets.Widget.getDisplay(Widget.java:554)
	at com.twinsoft.convertigo.eclipse.editors.StartupEditor$3.completed(StartupEditor.java:130)
	at com.twinsoft.convertigo.eclipse.swt.C8oBrowser.lambda$4(C8oBrowser.java:186)
	at com.teamdev.jxbrowser.event.internal.NewObservableHelper.notifyObservers(NewObservableHelper.java:58)
	at com.teamdev.jxbrowser.internal.rpc.stream.EventStream.dispatch(EventStream.java:74)
	at com.teamdev.jxbrowser.internal.rpc.stream.EventStream.process(EventStream.java:126)
	at com.teamdev.jxbrowser.internal.rpc.stream.Stream$StreamObserver.lambda$onNext$0(Stream.java:164)
	at com.teamdev.jxbrowser.internal.BrowserThread$TaskRunner.processTasks(BrowserThread.java:139)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by nicolas-albert** [comment]
Ok for convertigo-09970-develop-7.9.0-beta
