### ISSUE TITLE
Information pop-up at Studio start up: Error in getProject

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#452]
**Studio Convertigo EMS Studio 7.9.0_beta (build 09978-develop-7.9.0-beta)**

![image](https://user-images.githubusercontent.com/1685373/105325845-56f12680-5bcd-11eb-8d98-68485cb4ed28.png)

```
eclipse.buildId=unknown
java.version=15.0.1
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.core.resources
Error
Thu Jan 21 09:42:03 CET 2021
Resource '/ServiceMail' already exists.

java.lang.Exception: Resource '/ServiceMail' already exists.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:309)
	at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:296)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:56)
	at org.eclipse.core.internal.resources.Project.create(Project.java:266)
	at org.eclipse.core.internal.resources.Project.create(Project.java:252)
	at com.twinsoft.convertigo.eclipse.ConvertigoPlugin.createProjectPluginResource(ConvertigoPlugin.java:1431)
	at com.twinsoft.convertigo.eclipse.ConvertigoPlugin.createProjectPluginResource(ConvertigoPlugin.java:1437)
	at com.twinsoft.convertigo.eclipse.ConvertigoPlugin.createProjectPluginResource(ConvertigoPlugin.java:1407)
	at com.twinsoft.convertigo.eclipse.ConvertigoPlugin.getProjectPluginResource(ConvertigoPlugin.java:1479)
	at com.twinsoft.convertigo.eclipse.ConvertigoPlugin.getProjectPluginResource(ConvertigoPlugin.java:1467)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.ProjectTreeObject.getIProject(ProjectTreeObject.java:806)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.ProjectTreeObject.getAdapter(ProjectTreeObject.java:971)
	at org.eclipse.ui.internal.LegacyResourceSupport.getAdaptedContributorResource(LegacyResourceSupport.java:414)
	at org.eclipse.ui.internal.decorators.DecoratorManager.getResourceAdapter(DecoratorManager.java:530)
	at org.eclipse.ui.internal.decorators.DecoratorManager.decorateText(DecoratorManager.java:418)
	at org.eclipse.ui.internal.decorators.DecoratorManager$ManagedWorkbenchLabelDecorator.decorateText(DecoratorManager.java:150)
	at org.eclipse.jface.viewers.DecoratingLabelProvider.getText(DecoratingLabelProvider.java:141)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.DecoratingColumnLabelProvider.getText(DecoratingColumnLabelProvider.java:61)
	at org.eclipse.jface.viewers.ColumnLabelProvider.update(ColumnLabelProvider.java:40)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:959)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:126)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1037)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:427)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2111)
	at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2775)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1960)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:677)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1936)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1893)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1879)
	at org.eclipse.jface.viewers.StructuredViewer.lambda$2(StructuredViewer.java:1461)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1400)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:363)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1361)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1461)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:526)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$2.lambda$0(ProjectExplorerView.java:414)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
```
In first screenshot, the testSOAP containing the WebService is not loaded yet, then:
![image](https://user-images.githubusercontent.com/1685373/105326137-b64f3680-5bcd-11eb-9346-955046413df9.png)

**Comment by gregory-vorbe** [comment]
The **ServiceMail** project in the treeview has the same connector.

**Comment by nathalie-lammelin** [comment]
> The **ServiceMail** project in the treeview has the same connector.

@gregory-vorbe : could you attach necessary projects for reproduction ? Thanks

**Comment by gregory-vorbe** [comment]
Here are the two projects named by the pop-up : 
[testSOAP.zip](https://github.com/convertigo/convertigo/files/5903486/testSOAP.zip)
[ServiceMail.zip](https://github.com/convertigo/convertigo/files/5903487/ServiceMail.zip)

**Comment by gregory-vorbe** [comment]
This was due to a workspace from an older 7.9.0 beta version. No pop-up when using a fresh workspace and importing the projects
