### ISSUE TITLE
Schema & Picker views are empty if a broken source exists in the project

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#484]
Step to reproduce:
1. create a Seq1
2. create a Seq2
3. create in Seq1 a CallSequence to Seq2
4. remove Seq2
5. the project have now a broken source
6. Schema view and picker are empty

A broken source can also appear if a project dependecy is missing (this can be normal).

It could be nice to:
1. don't break schema generation on broken source
2. a better UI warning about broken sources in a project (bubble !broken source! decoration to project ?)

**Comment by gregory-vorbe** [comment]
in **Convertigo version 7.9.3_beta (build 10800-hotfix-7.9.3-7.9.3-beta)**

- Create a project P1 with sequence S1
- Create a project P2 with sequence S2
- CTRL + Drag and Drop P2_S2 to P1_S1
- Call Sequence Step is created
- Add some Element XML Steps
- Delete permanently P2

Try to view source of Element Steps
Picker is empty and error log is filled

```
Unabled to build schema for project "P1"
com.twinsoft.convertigo.engine.EngineException: Error occured while building schema
	at com.twinsoft.convertigo.engine.XmlSchemaBuilderExecutor.buildSchema(XmlSchemaBuilderExecutor.java:129)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemaForProject(SchemaManager.java:566)
	at com.twinsoft.convertigo.engine.SchemaManager.getSchemasForProject(SchemaManager.java:496)
	at com.twinsoft.convertigo.eclipse.views.schema.SchemaView$14.run(SchemaView.java:527)
	at com.twinsoft.convertigo.eclipse.views.schema.SchemaView$2.run(SchemaView.java:180)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.concurrent.ExecutionException: com.twinsoft.convertigo.engine.EngineException: beginBuildSchema failed
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.twinsoft.convertigo.engine.XmlSchemaBuilderExecutor.buildSchema(XmlSchemaBuilderExecutor.java:100)
	... 5 more
Caused by: com.twinsoft.convertigo.engine.EngineException: beginBuildSchema failed
	at com.twinsoft.convertigo.engine.XmlSchemaBuilder.beginBuildSchema(XmlSchemaBuilder.java:172)
	at com.twinsoft.convertigo.engine.XmlSchemaBuilderExecutor$1.call(XmlSchemaBuilderExecutor.java:93)
	at com.twinsoft.convertigo.engine.XmlSchemaBuilderExecutor$1.call(XmlSchemaBuilderExecutor.java:90)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	... 1 more
Caused by: com.twinsoft.convertigo.engine.EngineException: midBuildSchema failed
	at com.twinsoft.convertigo.engine.XmlSchemaBuilder.midBuildSchema(XmlSchemaBuilder.java:789)
	at com.twinsoft.convertigo.engine.XmlSchemaBuilder.beginBuildSchema(XmlSchemaBuilder.java:170)
	... 8 more
Caused by: com.twinsoft.convertigo.engine.EngineException: Missing required or not loaded project "P2"
	at com.twinsoft.convertigo.engine.XmlSchemaBuilder$3.walk(XmlSchemaBuilder.java:603)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:346)
	at com.twinsoft.convertigo.engine.XmlSchemaBuilder$3.walk(XmlSchemaBuilder.java:446)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:85)
	at com.twinsoft.convertigo.engine.XmlSchemaBuilder$3.walk(XmlSchemaBuilder.java:772)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:66)
	at com.twinsoft.convertigo.engine.XmlSchemaBuilder.midBuildSchema(XmlSchemaBuilder.java:785)
	... 9 more
```

![image](https://user-images.githubusercontent.com/1685373/117016295-d9bc6e00-acf2-11eb-888c-5d8c24e6503c.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.3_beta (build 10808-hotfix-7.9.3-7.9.3-beta)**

Small typo in log: (XmlSchemaBuilder) Not **complet** schema because: Missing required or not loaded project "P2" => **complete**
