### ISSUE TITLE
Error on dynamic variable in HTTP transaction sub path property

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#545]
**Convertigo 7.9.6**

In an HTTP transaction "**Sub path**" property can contain dynamic variable names like **/mySubPath/{myVariable}/nextSubPath**
if **myVariable** value contains **$** character it throws an error, for example **var$123456**:
```<document>
    <error connector="HTTP_connector" project="JIRA_CONV_518" transaction="anything" type="c8o">
        <code>-1</code>
        <message>An unexpected error has occured while the execution of the requested object 'anything'.</message>
        <details>No group 1</details>
        <context/>
        <exception>com.twinsoft.convertigo.engine.EngineException</exception>
        <stacktrace>com.twinsoft.convertigo.engine.EngineException: An unexpected error has occured while the execution of the requested object 'anything'. 
	at com.twinsoft.convertigo.beans.core.RequestableObject.run(RequestableObject.java:362) 
	at com.twinsoft.convertigo.engine.cache.CacheManager.getDocument(CacheManager.java:168) 
	at com.twinsoft.convertigo.engine.Engine.getDocument(Engine.java:1323) 
	at com.twinsoft.convertigo.engine.requesters.GenericRequester.getDocument(GenericRequester.java:689) 
	at com.twinsoft.convertigo.engine.requesters.GenericRequester.coreProcessRequest(GenericRequester.java:617) 
	at com.twinsoft.convertigo.engine.requesters.GenericRequester.processRequest(GenericRequester.java:277) 
	at com.twinsoft.convertigo.engine.requesters.InternalRequester.processRequest(InternalRequester.java:73) 
	at com.twinsoft.convertigo.eclipse.ConvertigoPlugin$9.run(ConvertigoPlugin.java:1551) 
	at java.base/java.lang.Thread.run(Thread.java:831) 
Caused by: java.lang.IndexOutOfBoundsException: No group 1 
	at java.base/java.util.regex.Matcher.start(Matcher.java:482) 
	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1090) 
	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997) 
	at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181) 
	at java.base/java.lang.String.replaceAll(String.java:2142) 
	at com.twinsoft.convertigo.beans.connectors.HttpConnector.prepareForTransaction(HttpConnector.java:478) 
	at com.twinsoft.convertigo.beans.core.Transaction.initializeConnector(Transaction.java:162) 
	at com.twinsoft.convertigo.beans.core.TransactionWithVariables.initializeConnector(TransactionWithVariables.java:639) 
	at com.twinsoft.convertigo.beans.core.Transaction.prepareForRequestable(Transaction.java:167) 
	at com.twinsoft.convertigo.beans.core.RequestableObject$RequestableThread.run(RequestableObject.java:888) 
</stacktrace>
    </error>
</document>```

The value can be escaped with a back-slash to work: **var\$123456**

The replacement code for dynamic variables should sanitize the value to be processed by the Regex.

**Comment by nathalie-lammelin** [comment]
Closed. Should be backported to next `7.9.X hotfix`. Since build [11841](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-11841-develop-8.0.0-beta/)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 11913-develop-8.0.0-beta)**
