### ISSUE TITLE
[CLI] Build failed with NPE if a project dependency doesn't load

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#556]
```
Caused by: java.lang.NullPointerException
	at com.twinsoft.convertigo.engine.CLI.generateMobileBuilder(CLI.java:290)
	at com.convertigo.gradle.GenerateMobileBuilder.taskAction(GenerateMobileBuilder.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```
No clues to find which project failed.
The NPE should be detected with an explicite log.

**Comment by nicolas-albert** [comment]
Tested ok with a non existing project reference:
```
> Task :generateMobileBuilder
Caching disabled for task ':generateMobileBuilder' because:
  Build cache is disabled
Task ':generateMobileBuilder' is not up-to-date because:
  Task.upToDateWhen is false.
Failed to import project reference: lib_FakeDep (ignored)
:generateMobileBuilder (Thread[Execution worker for ':',5,main]) completed. Took 0.37 secs.
```
