### ISSUE TITLE
Can not import reference project of a 7.9.0 demo project

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#565]
**Convertigo EMS Studio 7.9.8_beta (build 12055-hotfix-7.9.8-7.9.8-beta)**

Importing BankingDemo project generates following error:

```
Failed to initialize mobile builder for project 'BankingDemo'
com.twinsoft.convertigo.engine.EngineException: Unable to write source files for page 'Chat'
	at com.twinsoft.convertigo.engine.mobile.Ionic3Builder.writePageSourceFiles(Ionic3Builder.java:2050)
	at com.twinsoft.convertigo.engine.mobile.Ionic3Builder.updateSourceFiles(Ionic3Builder.java:749)
	at com.twinsoft.convertigo.engine.mobile.Ionic3Builder.init(Ionic3Builder.java:596)
	at com.twinsoft.convertigo.engine.mobile.MobileBuilder.initBuilder(MobileBuilder.java:83)
	at com.twinsoft.convertigo.engine.mobile.MobileBuilder.initBuilder(MobileBuilder.java:77)
	at com.twinsoft.convertigo.engine.DatabaseObjectsManager.importProject(DatabaseObjectsManager.java:1211)
	at com.twinsoft.convertigo.engine.DatabaseObjectsManager.getOriginalProjectByName(DatabaseObjectsManager.java:332)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectLoadingJob.run(ProjectLoadingJob.java:106)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.twinsoft.convertigo.engine.EngineException: Unable to write ionic page ts file
	at com.twinsoft.convertigo.engine.mobile.Ionic3Builder.writePageTs(Ionic3Builder.java:1020)
	at com.twinsoft.convertigo.engine.mobile.Ionic3Builder.writePageSourceFiles(Ionic3Builder.java:2040)
	... 8 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.twinsoft.convertigo.beans.core.MobileApplication.getApplicationComponent()" because the return value of "com.twinsoft.convertigo.beans.core.Project.getMobileApplication()" is null
	at com.twinsoft.convertigo.beans.mobile.components.UIUseShared.getTargetSharedComponent(UIUseShared.java:344)
	at com.twinsoft.convertigo.beans.mobile.components.UIUseShared.addEventSubscriber(UIUseShared.java:282)
	at com.twinsoft.convertigo.beans.mobile.components.UIComponent.addEventSubscriber(UIComponent.java:417)
	at com.twinsoft.convertigo.beans.mobile.components.PageComponent.getUIEventSubscriberList(PageComponent.java:362)
	at com.twinsoft.convertigo.beans.mobile.components.PageComponent.computeScripts(PageComponent.java:893)
	at com.twinsoft.convertigo.beans.mobile.components.PageComponent.doComputeContents(PageComponent.java:695)
	at com.twinsoft.convertigo.beans.mobile.components.PageComponent.getComputedContents(PageComponent.java:680)
	at com.twinsoft.convertigo.beans.mobile.components.PageComponent.getComputedDeclarations(PageComponent.java:788)
	at com.twinsoft.convertigo.engine.mobile.Ionic3Builder.getPageTsContent(Ionic3Builder.java:1235)
	at com.twinsoft.convertigo.engine.mobile.Ionic3Builder.writePageTs(Ionic3Builder.java:1012)
	... 9 more
```
Guess this is due to missing lib project in reference: lib_AmazonLEX=https://github.com/convertigo/c8oprj-lib-amazonlex.git

Importing manually the lib_AmazonLEX from github seems to resolve the error (you have to import branch 7.7.0 from Github).

**Comment by gregory-vorbe** [comment]
https://convertigo-download.s3.us-east-1.amazonaws.com/webrepository/projects/BankingDemo.car

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.8_beta (build 12082-hotfix-7.9.8-7.9.8-beta)**
