### ISSUE TITLE
[NGX] Create a 'Create shared Component' Wizard on MobileComponent right Click

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#566]
Same as #552 but for NGX

**Comment by gregory-vorbe** [comment]
in **Convertigo EMS Studio 8.0.0_beta (build 12669-develop-8.0.0-beta)**

In **OffChat** demo application, Can not create a shared component of the **cardContainer** component in the **Content** component of the '**Lobby**' page.

![image](https://user-images.githubusercontent.com/1685373/156153438-18dc2487-9cf8-4b3d-9a55-18c10c26d90f.png)

```
eclipse.buildId=unknown
java.version=17.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

com.twinsoft.convertigo.eclipse.ConvertigoPlugin
Error
Tue Mar 01 10:53:24 CET 2022
Unable to create a new shared component!

java.lang.Exception: Unable to scan for variables
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard.scanForVariables(SharedComponentWizard.java:619)
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard.<init>(SharedComponentWizard.java:105)
	at com.twinsoft.convertigo.eclipse.popup.actions.NgxSharedComponentExtractAction.run(NgxSharedComponentExtractAction.java:125)
	at com.twinsoft.convertigo.eclipse.popup.actions.MyAbstractAction.run(MyAbstractAction.java:109)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:239)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.lang.NullPointerException: Cannot invoke "com.twinsoft.convertigo.beans.ngx.components.MobileSmartSource.toJsonString()" because the return value of "com.twinsoft.convertigo.beans.ngx.components.MobileSmartSourceType.getSmartSource()" is null
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard$2.scanSmartSource(SharedComponentWizard.java:526)
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard$2.walk(SharedComponentWizard.java:590)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:301)
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard$2.walk(SharedComponentWizard.java:613)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:301)
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard$2.walk(SharedComponentWizard.java:613)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:301)
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard$2.walk(SharedComponentWizard.java:613)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:301)
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard$2.walk(SharedComponentWizard.java:613)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:66)
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard$2.init(SharedComponentWizard.java:566)
	at com.twinsoft.convertigo.eclipse.wizards.new_ngx.SharedComponentWizard.scanForVariables(SharedComponentWizard.java:617)
	... 32 more
```

Maybe the TS is a bit complex, but is it possible to have more information on what failed ?

**Comment by nathalie-lammelin** [comment]
Because the `If(item1517843119306 != this.window.sessionStorage.username)` has an SC source which is null

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12759-develop-8.0.0-beta)**
