### ISSUE TITLE
Error while introspecting parameter "animationName"

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#575]
Convertigo EMS Studio 8.0.0_beta (build 12264-develop-8.0.0-beta)

Starting the Studio with an opened project containing the Animate component generates the following error.
Maybe not related, but that happened after converting a MBv3 to a MBv6 project:

![image](https://user-images.githubusercontent.com/1685373/152763481-836bf709-5a10-4218-baf5-95a5e870401b.png)

```
eclipse.buildId=unknown
java.version=17.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Command-line arguments:  -os win32 -ws win32 -arch x86_64

com.twinsoft.convertigo.eclipse.ConvertigoPlugin
Error
Mon Feb 07 10:37:00 CET 2022
Error while introspecting parameter "animationName"

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.DatabaseObjectTreeObject.findPropertyDescriptor(DatabaseObjectTreeObject.java:477)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.DatabaseObjectTreeObject.getDescriptors(DatabaseObjectTreeObject.java:367)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.DatabaseObjectTreeObject.<init>(DatabaseObjectTreeObject.java:172)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.NgxComponentTreeObject.<init>(NgxComponentTreeObject.java:54)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.NgxUIComponentTreeObject.<init>(NgxUIComponentTreeObject.java:114)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:1745)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:301)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:2046)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:301)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:2046)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:269)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:2046)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:254)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:2046)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:127)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:2046)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.walk(WalkHelper.java:105)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.walk(ProjectExplorerView.java:2046)
	at com.twinsoft.convertigo.engine.helpers.WalkHelper.init(WalkHelper.java:66)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView$11.init(ProjectExplorerView.java:1565)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView.loadDatabaseObject(ProjectExplorerView.java:2056)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView.loadDatabaseObject(ProjectExplorerView.java:1544)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectLoadingJob.loadDatabaseObject(ProjectLoadingJob.java:303)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectLoadingJob.run(ProjectLoadingJob.java:183)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1233)
	at java.base/java.util.Arrays$ArrayList.sort(Arrays.java:4219)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at com.twinsoft.convertigo.beans.ngx.components.CssAnimation.names(CssAnimation.java:161)
	at com.twinsoft.convertigo.beans.ngx.components.UIAnimation.getTagsForProperty(UIAnimation.java:82)
	at com.twinsoft.convertigo.eclipse.property_editors.StringComboBoxPropertyDescriptor.getTags(StringComboBoxPropertyDescriptor.java:269)
	... 29 more

```

**Comment by gregory-vorbe** [comment]
Since **Convertigo EMS Studio 8.0.0_beta (build 12273-develop-8.0.0-beta)** i do not have the alert pop-up any more, nor the message in Error Log view.

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe : could you attach your project for reproduction

**Comment by gregory-vorbe** [comment]
I got the error back in Convertigo EMS Studio 8.0.0_beta (build 12273-develop-8.0.0-beta)

[testMBv6.zip](https://github.com/convertigo/convertigo/files/8024232/testMBv6.zip)
[testMBv3.zip](https://github.com/convertigo/convertigo/files/8024233/testMBv3.zip)

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe : both projects are NGX projects and are the same

**Comment by nathalie-lammelin** [comment]
Closed: non reproductable

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 8.0.0_beta (build 12741-develop-8.0.0-beta)**
