### ISSUE TITLE
Execution of TestCase with default variable's value set to <null> fails

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#580]
Since 7.9.7 #536

Stacktrace in 8.0.0
`An unexpected error has occured while trying to execute the transaction.
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "parameterObject" is null
	at com.twinsoft.convertigo.engine.translators.DefaultInternalTranslator.addParameterObject(DefaultInternalTranslator.java:99)
	at com.twinsoft.convertigo.engine.translators.DefaultInternalTranslator.buildInputDocument(DefaultInternalTranslator.java:84)
	at com.twinsoft.convertigo.engine.requesters.GenericRequester.makeInputDocument(GenericRequester.java:601)
	at com.twinsoft.convertigo.engine.requesters.GenericRequester.coreProcessRequest(GenericRequester.java:613)
	at com.twinsoft.convertigo.engine.requesters.GenericRequester.processRequest(GenericRequester.java:277)
	at com.twinsoft.convertigo.engine.requesters.InternalRequester.processRequest(InternalRequester.java:79)
	at com.twinsoft.convertigo.eclipse.ConvertigoPlugin$9.run(ConvertigoPlugin.java:1565)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by nathalie-lammelin** [comment]
![Screenshot 2022-03-04 170800](https://user-images.githubusercontent.com/27724039/156800682-4a47f232-9037-4187-af4c-1f4461509fc6.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12741-develop-8.0.0-beta)**

**Comment by nathalie-lammelin** [comment]
Closed at build v**12778**
