### ISSUE TITLE
[Studio] NPE on MacOS when try to deploy or export an unbuild project

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#614]
Sample of error when we try to deploy:
```
java.lang.NoSuchFieldError: handle
at com.twinsoft.convertigo.eclipse.swt.SwtUtils.applyStyle(SwtUtils.java:108)
at com.twinsoft.convertigo.eclipse.dialogs.ArchiveExportOptionDialog.createDialogArea(ArchiveExportOptionDialog.java:108)
```
This is the apply of the red color style.

**Comment by nicolas-albert** [comment]
Ok for **convertigo-13647-hotfix-8.0.1-8.0.1-beta**.
