### ISSUE TITLE
Null error when delete a project

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#75]
When deleting a project, this error can happen:
![image](https://user-images.githubusercontent.com/225279/53871812-46495e80-3ffd-11e9-9c39-4be8b1b3254f.png)

```
ENTRY com.twinsoft.convertigo.eclipse.ConvertigoPlugin 2 0 2019-03-05 18:52:07.399
!MESSAGE Could not update Transaction step"Call_Transaction1" !
null
!STACK 0
java.lang.NullPointerException
    at com.twinsoft.convertigo.eclipse.ConvertigoPlugin.getActivePage(ConvertigoPlugin.java:1288)
    at com.twinsoft.convertigo.eclipse.ConvertigoPlugin.getProjectExplorerView(ConvertigoPlugin.java:1298)
    at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.StepTreeObject.treeObjectRemoved(StepTreeObject.java:191)
    at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView.fireTreeObjectRemoved(ProjectExplorerView.java:812)
    at com.twinsoft.convertigo.eclipse.popup.actions.UnloadedProjectDeleteAction$1.run(UnloadedProjectDeleteAction.java:85)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by gregory-vorbe** [comment]
Ok in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**
