### ISSUE TITLE
Right click on the mobile viewer to highlight a component may break

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#779]
If you right-click on the mobile viewer during the initial compilation phase of an application, this causes the "Right-click on mobile viewer to highlight a component" functionality to be interrupted until the we close and reopen the mobile viewer.

It seems that an error is not properly catched, see stdout:
```log
Exception in thread "Browser Thread: 4cf25770-4bfd-41bd-ba89-32eb1a8fd95b" com.teamdev.jxbrowser.js.JsException: No such function
	at com.teamdev.jxbrowser.js.internal.JsObjectImpl.callMethod(JsObjectImpl.java:175)
	at com.teamdev.jxbrowser.js.internal.JsObjectImpl.call(JsObjectImpl.java:153)
	at com.twinsoft.convertigo.eclipse.swt.C8oBrowser.executeFunctionAndReturnValue(C8oBrowser.java:295)
	at com.twinsoft.convertigo.eclipse.editors.ngx.ApplicationComponentEditor.highlightPoint(ApplicationComponentEditor.java:1761)
	at com.twinsoft.convertigo.eclipse.editors.ngx.ApplicationComponentEditor.highlightPoint(ApplicationComponentEditor.java:1749)
	at com.twinsoft.convertigo.eclipse.editors.ngx.ApplicationComponentEditor.lambda$1(ApplicationComponentEditor.java:511)
	at com.teamdev.jxbrowser.internal.rpc.stream.CallbackStream.process(CallbackStream.java:178)
	at com.teamdev.jxbrowser.internal.rpc.stream.Stream$StreamObserver.lambda$onNext$0(Stream.java:167)
	at com.teamdev.jxbrowser.internal.RpcThreadImpl$TaskRunner.processTasks(RpcThreadImpl.java:172)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by gregory-vorbe** [comment]
No reproduced in **Convertigo EMS Studio 8.2.4_beta (build 17301-hotfix-8.2.4-8.2.4-beta)**
