### ISSUE TITLE
[Step] Rename file : Using same name for Source and New name properties deletes the file and generates an error

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#784]
Convertigo EMS Studio 8.2.3 (build 16572-8.2.3)

![image](https://github.com/convertigo/convertigo/assets/1685373/f110d405-ba0d-464e-bb6d-242e2c751d46)

The source file is deleted and it generates the following error (with a typo!):
```
<?xml version="1.0" encoding="UTF-8"?><document>
    <error project="step_rename" sequence="rename" type="c8o">
        <code>-1</code>
        <message>An exception occured while executing step</message>
        <details>Unablie to rename the file or directory "C:\Convertigo\Studio 8.2.3\workspace\step_rename\destination\Kawaii-PNG-Pic2-copy.png" renamed to "Kawaii-PNG-Pic2-copy.png"., Source 'C:\Convertigo\Studio 8.2.3\workspace\step_rename\destination\Kawaii-PNG-Pic2-copy.png' does not exist</details>
        <context/>
        <exception>com.twinsoft.convertigo.engine.EngineException</exception>
        <stacktrace>com.twinsoft.convertigo.engine.EngineException: An exception occured while executing step 
	at com.twinsoft.convertigo.beans.core.Step.execute(Step.java:631) 
	at com.twinsoft.convertigo.beans.core.Sequence.executeNextStep(Sequence.java:1553) 
	at com.twinsoft.convertigo.beans.core.Sequence.executeNextStep(Sequence.java:1237) 
	at com.twinsoft.convertigo.beans.sequences.GenericSequence.runCore(GenericSequence.java:41) 
	at com.twinsoft.convertigo.beans.core.RequestableObject$RequestableThread.run(RequestableObject.java:901) 
Caused by: com.twinsoft.convertigo.engine.EngineException: Unablie to rename the file or directory "C:\Convertigo\Studio 8.2.3\workspace\step_rename\destination\Kawaii-PNG-Pic2-copy.png" renamed to "Kawaii-PNG-Pic2-copy.png". 
	at com.twinsoft.convertigo.beans.steps.RenameStep.stepExecute(RenameStep.java:126) 
	at com.twinsoft.convertigo.beans.core.Step.execute(Step.java:626) 
	... 4 more 
Caused by: java.io.FileNotFoundException: Source 'C:\Convertigo\Studio 8.2.3\workspace\step_rename\destination\Kawaii-PNG-Pic2-copy.png' does not exist 
	at org.apache.commons.io.FileUtils.validateMoveParameters(FileUtils.java:3124) 
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2303) 
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2283) 
	at com.twinsoft.convertigo.beans.steps.RenameStep.stepExecute(RenameStep.java:116) 
	... 5 more 
</stacktrace>
    </error>
</document><!--
Generated by Convertigo Enterprise Mobility Server
Requester: InternalRequester
-->
```

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.4_beta (build 17301-hotfix-8.2.4-8.2.4-beta)**
