### ISSUE TITLE
Invalid Thread Access when importing a project from GIT with <project>=<git url>

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#821]
Importing a project causes 

!ENTRY com.twinsoft.convertigo.eclipse.ConvertigoPlugin 1 0 2024-04-16 10:44:44.493
!MESSAGE Import project from file ""

!ENTRY com.twinsoft.convertigo.eclipse.ConvertigoPlugin 4 0 2024-04-16 10:44:44.501
!MESSAGE Error while loading project AlloToulouse
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1209)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:708)
	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1372)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.ProjectTreeObject.save(ProjectTreeObject.java:280)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.model.ProjectTreeObject.close(ProjectTreeObject.java:144)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView.unloadProjectTreeObject(ProjectExplorerView.java:2397)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ViewContentProvider.reloadProject(ViewContentProvider.java:215)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ViewContentProvider.reloadProject(ViewContentProvider.java:193)
	at com.twinsoft.convertigo.eclipse.views.projectexplorer.ProjectExplorerView.reloadProject(ProjectExplorerView.java:2470)
	at com.twinsoft.convertigo.eclipse.wizards.import_export.ImportWizard.lambda$0(ImportWizard.java:68)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Looking at the code in package com.twinsoft.convertigo.eclipse.views.projectexplorer.model  in save() method the is no 

Display.getDefault().syncExec(new Runnable() {
    public void run() {
  ...
}
Pattern ..

**Comment by nicolas-albert** [comment]
Note to reproduce: the project should already exist

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 8.3.0_beta (build 19117-develop-8.3.0-beta)**
