### ISSUE TITLE
Generating Schema form connector data fails if Documentation of imported REST Swagger contains illegal characters.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#824]
Steps to reproduce : 

- Import https://data.toulouse-metropole.fr/api/explore/v2.1/console Swagger Services
- Execute the getRecords Method with dataset_id set to 'dmt_jour_de_collecte'
- Execute "Update schema from current connector data"

`Fatal Error] :128:3: The element type "FACETVALUE" must be terminated by the matching end-tag "</FACETVALUE>".
org.xml.sax.SAXParseException; lineNumber: 128; columnNumber: 3; The element type "FACETVALUE" must be terminated by the matching end-tag "</FACETVALUE>".
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at com.twinsoft.convertigo.engine.util.XMLUtils.parseDOMFromString(XMLUtils.java:900)
	at com.twinsoft.convertigo.beans.core.Transaction.writeSchemaToFile(Transaction.java:647)
	at com.twinsoft.convertigo.eclipse.popup.actions.UpdateXSDTypesAction.run(UpdateXSDTypesAction.java:159)
	at com.twinsoft.convertigo.eclipse.popup.actions.MyAbstractAction.run(MyAbstractAction.java:115)
	at com.twinsoft.convertigo.eclipse.popup.actions.UpdateXSDTypesAction.run(UpdateXSDTypesAction.java:1)`

The documentation for getRecords variable refine holds some illegal  characters : 

`
Refinement uses the following syntax: `refine=&lt;FACETNAME&gt;:&lt;FACETVALUE&gt;`
`

**Comment by nicolas-albert** [comment]
Due to xml building by string: https://github.com/convertigo/convertigo/blob/a5e7ceb431ba0ec68c0c20fbe64d380adb9350cf/engine/src/com/twinsoft/convertigo/beans/core/TransactionWithVariables.java#L770

**Comment by nicolas-albert** [comment]
Escape removed 8 months ago:
https://github.com/convertigo/convertigo/commit/00ac2e3390ad9224aa8b6124c94bac803c49137e

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19057-develop-8.3.0-beta)**
