### ISSUE TITLE
Adding a Component requiring additional packages causes a Invalid Thread Exception.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#85]
```
(MobileBuilder) Throwable catched
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:373)
	at org.eclipse.swt.widgets.Control.getBackground(Control.java:1185)
	at com.twinsoft.convertigo.eclipse.swt.SwtUtils.isDark(SwtUtils.java:48)
	at com.twinsoft.convertigo.eclipse.editors.mobile.ApplicationComponentEditor.launchBuilder(ApplicationComponentEditor.java:1161)
	at com.twinsoft.convertigo.eclipse.editors.mobile.ApplicationComponentEditor.launchBuilder(ApplicationComponentEditor.java:1155)
	at com.twinsoft.convertigo.eclipse.editors.mobile.ApplicationComponentEditor.onPackageUpdated(ApplicationComponentEditor.java:1493)
	at com.twinsoft.convertigo.engine.mobile.MobileBuilder.firePackageUpdated(MobileBuilder.java:317)
	at com.twinsoft.convertigo.engine.mobile.MobileBuilder$MbWorker.process(MobileBuilder.java:136)
	at com.twinsoft.convertigo.engine.mobile.MobileBuilder$MbWorker.run(MobileBuilder.java:224)
	at java.lang.Thread.run(Unknown Source)


```
This  happens for example when we drag a MAP in a project

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 7.6.0 (build 03826-release-7.6.0-7.6.0)**
