### ISSUE TITLE
[Studio] Failed to import samples

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#854]
When we try to import samples in the Studio, the following error occurs:
![Capture d’écran 2024-09-18 à 10 34 28](https://github.com/user-attachments/assets/f8586c73-c816-48c9-9439-f921a68112b6)

Here the complete ErrorLog:
```
com.twinsoft.convertigo.engine.EngineException: Failed to load project from 'https://github.com/convertigo/c8oprj-sample-offchat/archive/8.3.0.zip' because of [EngineException] Unable to deploy the project from the file "C:\Users\nicol\AppData\Local\Temp\convertigoImportFromHttp8071361315486506980.car".
    at com.twinsoft.convertigo.engine.DatabaseObjectsManager.deployProject(DatabaseObjectsManager.java:807)
    at com.twinsoft.convertigo.engine.DatabaseObjectsManager.deployProject(DatabaseObjectsManager.java:780)
    at com.twinsoft.convertigo.engine.ReferencedProjectManager.importProject(ReferencedProjectManager.java:184)
    at com.twinsoft.convertigo.eclipse.wizards.new_project.NewProjectWizard.lambda$3(NewProjectWizard.java:601)
    at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.twinsoft.convertigo.engine.EngineException: Unable to deploy the project from the file "C:\Users\nicol\AppData\Local\Temp\convertigoImportFromHttp8071361315486506980.car".
    at com.twinsoft.convertigo.engine.DatabaseObjectsManager.deployProject(DatabaseObjectsManager.java:864)
    at com.twinsoft.convertigo.engine.DatabaseObjectsManager.deployProject(DatabaseObjectsManager.java:789)
    at com.twinsoft.convertigo.engine.DatabaseObjectsManager.deployProject(DatabaseObjectsManager.java:804)
    ... 5 more
Caused by: java.lang.IllegalStateException: No match found
    at java.base/java.util.regex.Matcher.checkMatch(Matcher.java:1852)
    at java.base/java.util.regex.Matcher.group(Matcher.java:687)
    at com.twinsoft.convertigo.engine.util.ZipUtils.getProjectName(ZipUtils.java:196)
    at com.twinsoft.convertigo.engine.DatabaseObjectsManager.deployProject(DatabaseObjectsManager.java:813)
    ... 7 more
```
This should be fixed!

**Comment by nicolas-albert** [comment]
Due to the same name `8.3.0` for branch and tag, for each samples.
